name: Deploy to github pages
on:
  push:
    branches:
      - main
jobs:
  gh-pages-deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v3.0.0
        
      - name: Checkout branch
        uses: actions/checkout@v3.0.0
        with:
          ref: ${{ github.head_ref }}

      - name: Clean install dependencies
        run: npm ci

      - name: Run deploy script
        run: |
          git config user.name "piergiorgioladisa" && git config user.email "44639444+piergiorgioladisa@users.noreply.github.com"
          npm i --save @fortawesome/fontawesome-svg-core
          npm run deploy
